version: '3.4'

services:
  microtask.services.tasks.api:
    image: ${DOCKER_REGISTRY-}microtaskservicestasksapi
    build:
      context: .
      dockerfile: MicroTask.Services.Tasks.Api/Dockerfile

  microtask.services.users.api:
    image: ${DOCKER_REGISTRY-}microtaskservicesusersapi
    build:
      context: .
      dockerfile: MicroTask.Services.Users.Api/Dockerfile


  microtask.services.categories.api:
    image: ${DOCKER_REGISTRY-}microtaskservicescategoriesapi
    build:
      context: .
      dockerfile: MicroTask.Services.Categories.Api/Dockerfile


  microtask.services.comments.api:
    image: ${DOCKER_REGISTRY-}microtaskservicescommentsapi
    build:
      context: .
      dockerfile: MicroTask.Services.Comments.Api/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
    expose:
     - 15672
     - 5672
